id: PA80808CF
initial_creation_type: input
source_metadata:
  title: Tupten Chöpel
  language: zh
  description: 'Texts by the great Khenpo Tupten Chöpel (thub bstan chos ''phel, 1886–1956)
    also known as Tubga Yishyin Norbu (thub dga'' yid bzhin nor bu) of Changma hermitage
    in Dzachukha:'
  volume:
    052931f7fef94a1d970d6f4577f6f320:
      title: Aspiration Prayer
      parent: Aspiration Prayers
created_at: '2022-03-01T02:00:07.178579'
last_modified_at: '2022-03-01T02:00:07.178582'
